Updated OAuth documentation.
code42/developer.code42.com pull request #108
Opened 2023-06-23 14:20 UTC by jdullum

2023-06-23 15:01 UTC, amoravec submitted a review, later dismissed

2023-06-23 15:36 UTC, tora-kozic approved these changes

2023-06-27 18:56 UTC, annie-payseur requested changes

2023-06-27 18:56 UTC, annie-payseur commented on source/api/user-guides/get_started.rmd
> +API calls require an authentication token in the header of the request. To obtain an authentication token, [create an API client](https://support.code42.com/Administrator/Cloud/Code42_console_referen
Link should be this URL: https://support.code42.com/hc/en-us/articles/14827617150231

2023-08-03 19:47 UTC, tora-kozic approved these changes

2023-08-14 15:48 UTC, merged